name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: npm test
      run: |
        npm test 
      env:
        CI: true
    - name: npm build
      run: |
        npm run build --if-present
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "jasylwong@gmail.com"
        git config --global user.name "jasylwong"
        git remote set-url origin https://${REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/jasylwong/radio-active.git
        npm run deploy